// RealKana Frequency Level 2 vocabulary.
// Readings: RealKana. Meanings and character notes: JMdict/KANJIDIC-style glosses.
window.INK_RUN_LEVEL_2_WORDS = [
  "頭",
  "態度",
  "着る",
  "式",
  "保存",
  "国際",
  "万",
  "例えば",
  "白い",
  "命",
];

window.INK_RUN_LEVEL_2_IMPORTS = [
  {
    word: "頭",
    reading: "あたま",
    romaji: ["atama"],
    meaning: "head; mind; brains; top; beginning",
    breakdown: [["頭", "あたま", "head; top; beginning"]],
    memory: "頭 is read あたま: head.",
  },
  {
    word: "態度",
    reading: "たいど",
    romaji: ["taido"],
    meaning: "attitude; manner; behavior; approach",
    breakdown: [["態", "たい", "condition; appearance; state"], ["度", "ど", "degree; extent; occasion"]],
    memory: "態 is たい and 度 is ど: たい + ど = たいど.",
  },
  {
    word: "着る",
    reading: "きる",
    romaji: ["kiru"],
    meaning: "to wear; to put on (clothes above the waist)",
    breakdown: [["着", "き", "wear; put on; arrive"], ["る", "る", "verb ending"]],
    memory: "着 gives き; add る: き + る = きる.",
  },
  {
    word: "式",
    reading: "しき",
    romaji: ["shiki", "siki"],
    meaning: "ceremony; style; system; formula; expression",
    breakdown: [["式", "しき", "ceremony; style; formula"]],
    memory: "式 is read しき: ceremony, style, or formula.",
  },
  {
    word: "保存",
    reading: "ほぞん",
    romaji: ["hozon"],
    meaning: "preservation; conservation; storage; saving (data)",
    breakdown: [["保", "ほ", "protect; preserve; maintain"], ["存", "ぞん", "exist; remain; preserve"]],
    memory: "保 is ほ and 存 is ぞん: ほ + ぞん = ほぞん.",
  },
  {
    word: "国際",
    reading: "こくさい",
    romaji: ["kokusai"],
    meaning: "international; diplomatic intercourse",
    breakdown: [["国", "こく", "country; nation"], ["際", "さい", "occasion; boundary; connection"]],
    memory: "国 is こく and 際 is さい: こく + さい = こくさい.",
  },
  {
    word: "万",
    reading: "まん",
    romaji: ["man"],
    meaning: "ten thousand; myriad; all",
    breakdown: [["万", "まん", "ten thousand; myriad"]],
    memory: "万 is read まん: ten thousand.",
  },
  {
    word: "例えば",
    reading: "たとえば",
    romaji: ["tatoeba"],
    meaning: "for example; for instance",
    breakdown: [["例", "たと", "example; instance"], ["えば", "えば", "kana ending"]],
    memory: "例 gives たと; add えば: たと + えば = たとえば.",
  },
  {
    word: "白い",
    reading: "しろい",
    romaji: ["shiroi", "siroi"],
    meaning: "white",
    breakdown: [["白", "しろ", "white"], ["い", "い", "adjective ending"]],
    memory: "白 is しろ; add い: しろ + い = しろい.",
  },
  {
    word: "命",
    reading: "いのち",
    romaji: ["inochi", "inoti"],
    meaning: "life; life force; lifetime; most important thing",
    breakdown: [["命", "いのち", "life; fate; command"]],
    memory: "命 is read いのち: life.",
  },
];
